// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4UBCwwSTe4cjHfa8371Uz1Ugld6ry018',
    appId: '1:8087077657:web:cd3415172f8a1d5261fb88',
    messagingSenderId: '8087077657',
    projectId: 'kefaproject',
    authDomain: 'kefaproject.firebaseapp.com',
    storageBucket: 'kefaproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPwUFpW_GlUj7hfbQwzt8GIg5yLYotflk',
    appId: '1:8087077657:android:467a55e7833d38f661fb88',
    messagingSenderId: '8087077657',
    projectId: 'kefaproject',
    storageBucket: 'kefaproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5lJIzTUg6fdEHjKcO9fCtimJNRPOtpso',
    appId: '1:8087077657:ios:ec08693b58203f9061fb88',
    messagingSenderId: '8087077657',
    projectId: 'kefaproject',
    storageBucket: 'kefaproject.firebasestorage.app',
    iosBundleId: 'com.example.kefa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5lJIzTUg6fdEHjKcO9fCtimJNRPOtpso',
    appId: '1:8087077657:ios:ec08693b58203f9061fb88',
    messagingSenderId: '8087077657',
    projectId: 'kefaproject',
    storageBucket: 'kefaproject.firebasestorage.app',
    iosBundleId: 'com.example.kefa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4UBCwwSTe4cjHfa8371Uz1Ugld6ry018',
    appId: '1:8087077657:web:71137763e1a8cec761fb88',
    messagingSenderId: '8087077657',
    projectId: 'kefaproject',
    authDomain: 'kefaproject.firebaseapp.com',
    storageBucket: 'kefaproject.firebasestorage.app',
  );
}
